version: "3"

services:
  client:
    container_name: url_shortener_client
    image: nginx:1.19.1-alpine
    networks:
      - short-url-net

  api:
    container_name: url_shortener_api
    restart: always
    build: ./api
    depends_on:
      - redis
    networks:
      - short-url-net
    command: ["npm", "run", "dev"]
    # command: ["nodemon", "/usr/src/app/src/index.js"]
    volumes:
      - ./api/app/src:/usr/src/app/src

  redis:
    container_name: url_shortener_redis
    image: redis:6.0.6-alpine3.12
    command: ["redis-server", "/data/redis.conf"]
    volumes:
      - ./redis:/data:rw
    networks:
      - short-url-net

networks:
  short-url-net:
    driver: bridge
